### ISSUE TITLE
Informazioni script

### ISSUE THREAD

**Issue by DDurim** [RiccardoColella/ClickDay#3]
Salve, il tuo script è molto interessante. Potresti dirmi se nello stato corrente è in grado di funzionare correttamente durante il click day?
Potresti anche fornire qualche informazioni in più sulla configurazione?

**Comment by DDurim** [comment]
Ottengo i seguenti errori durante l'esecuzione
C:\Users\User\Downloads\ClickDay-master\ClickDay-master\automator.py:126: SyntaxWarning: invalid escape sequence '\*'
  if re.search("^\* Inserire .* ultim", text_id_req):
C:\Users\User\Downloads\ClickDay-master\ClickDay-master\automator.py:158: SyntaxWarning: invalid escape sequence '\*'
  if re.search("^\* Data di domani \[GG/MM/AAAA]", data_question):
C:\Users\User\Downloads\ClickDay-master\ClickDay-master\automator.py:160: SyntaxWarning: invalid escape sequence '\*'
  elif re.search("^\* Data odierna \[GG/MM/AAAA]", data_question):
Traceback (most recent call last):
  File "C:\Users\User\Downloads\ClickDay-master\ClickDay-master\automator.py", line 21, in <module>
    driver.get(secret_data['login_page'])
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=125.0.6422.142)
Stacktrace:
        GetHandleVerifier [0x00007FF7170B1F52+60322]
        (No symbol) [0x00007FF71702CEC9]
        (No symbol) [0x00007FF716EE7CE9]
        (No symbol) [0x00007FF716ECFCCE]
        (No symbol) [0x00007FF716ECE1E5]
        (No symbol) [0x00007FF716ECE9DC]
        (No symbol) [0x00007FF716EEAC91]
        (No symbol) [0x00007FF716F7C5FE]
        (No symbol) [0x00007FF716F5C21A]
        (No symbol) [0x00007FF716F7BC80]
        (No symbol) [0x00007FF716F5BFC3]
        (No symbol) [0x00007FF716F29617]
        (No symbol) [0x00007FF716F2A211]
        GetHandleVerifier [0x00007FF7173C94AD+3301629]
        GetHandleVerifier [0x00007FF7174136D3+3605283]
        GetHandleVerifier [0x00007FF717409450+3563680]
        GetHandleVerifier [0x00007FF717164326+790390]
        (No symbol) [0x00007FF71703750F]
        (No symbol) [0x00007FF717033404]
        (No symbol) [0x00007FF717033592]
        (No symbol) [0x00007FF717022F9F]
        BaseThreadInitThunk [0x00007FFA2A9D7344+20]
        RtlUserThreadStart [0x00007FFA2BBE26B1+33]

**Comment by DDurim** [comment]
Sono riuscito a risolvere i primi 3 errori usando delle raw string visto che \* non è un backslash riconosciuto da python

**Comment by RiccardoColella** [comment]
Ciao! Riguardo alla prima domanda sul funzionamento durante la data del ClickDay: lo escludo perchè lo script è stato creato in maniera empirica deduttiva, io non sono in possesso di informazioni ufficiali sul form del ClickDay. Se da qualche parte fosse descritto in dettaglio come è composta la pagina del ClickDay ufficiale, allora si potrebbe pensare di svilupparci qualcosa sopra.
Che informazioni in più sulla configurazione vorresti sapere? Non mi è chiara la domanda
